### ISSUE TITLE
The Two Node Example Does Not Actually Configure a Shared Channel

### ISSUE THREAD

**Issue by mathisonryan** [DBOMproject/deployments#11]
**URL(s) with the issue:**

https://github.com/DBOMproject/deployments/blob/2.0.0-alpha-1/docker-compose-example-two-nodes/testAPIs.sh

https://github.com/DBOMproject/deployments/blob/2.0.0-alpha-1/docker-compose-example-two-nodes/README.md

**Description of the issue:**

From what I can tell, in order to set up a channel shared between two nodes, you need to use federation. However, from the README and the test.sh, I don't see any federation occurring. I can understand for the single node example where this makes sense, but a two node example really only makes sense when a shared channel is set up as that is what most solutions are looking for an example of. Especially with the certificate generation already set up for federation, a shared channel should be set up

**Submitting a pull request?**

Are you willing to submit a pull request to solve this issue? (Yes/No): Yes

**Comment by irajeshegde** [comment]
@mathisonryan - we do have a script for this, which is internal right now. I will update it soon and you can help us to enhance it.

**Comment by irajeshegde** [comment]
Scripts for the federation are updated. For more details refer [this](https://github.com/DBOMproject/deployments/commit/d14f471a5a8a507805ee9b1dbc8e88ed82c1d3a9) commit
