### ISSUE TITLE
 Duplicate Certs Generation

### ISSUE THREAD

**Issue by mathisonryan** [DBOMproject/deployments#12]
**Description of the issue:**

https://github.com/DBOMproject/deployments/blob/2.0.0-alpha-1/docker-compose-example-two-nodes/README.md

In the 2 node setup, it has you run cert generation, but then the cert generation runs again when the overall docker file is run

![image](https://github.com/DBOMproject/deployments/assets/57193503/013f59ca-bb28-4c2c-810e-6915436d35b5)

https://github.com/DBOMproject/deployments/blob/2.0.0-alpha-1/docker-compose-example-two-nodes/docker-compose.yml

![image](https://github.com/DBOMproject/deployments/assets/57193503/a84ff3c3-e407-4664-bfed-b045418bad85)

Seems to me that it should just be one or the other as you are just overwriting the certs again when you start the compose file

**Submitting a pull request?**

Are you willing to submit a pull request to solve this issue? (Yes/No): Yes

**Comment by irajeshegde** [comment]
@mathisonryan - Fixed it [more details](https://github.com/DBOMproject/deployments/commit/6a1ea231b54a50482097fc790d7504d68cdc1aef)
