### ISSUE TITLE
Incorrect comment

### ISSUE THREAD

**Issue by mathisonryan** [DBOMproject/deployments#13]
**URL(s) with the issue:**

[Please provide a link to the documentation entry](https://github.com/DBOMproject/deployments/tree/2.0.0-alpha-1/docker-compose-quickstart#stopping-docker-containers)

**Description of the issue:**

Small nitpick, need to remove the also removes volumes

![image](https://github.com/DBOMproject/deployments/assets/57193503/7521c306-6b96-4931-835c-5e1991e4041f)

**Submitting a pull request?**

Are you willing to submit a pull request to solve this issue? (Yes/No): Yes

**Comment by irajeshegde** [comment]
Thanks for identifying this. It's now updated in [commit](https://github.com/DBOMproject/deployments/commit/b4ea9d0607d67dbb4bd1dd78bcedff3c4b640534)
